version: '3.8'

services:
  rasa:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./config.yml:/app/config.yml
      - ./credentials.yml:/app/credentials.yml
      - ./domain.yml:/app/domain.yml
      - ./endpoints.yml:/app/endpoints.yml
    ports:
      - "5005:5005"
    depends_on:
      - action_server

  action_server:
    build: ./actions
    volumes:
      - ./actions:/app
    ports:
      - "5055:5055"
